[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:python]
command=python main.py
environment=PORT="8001",DATA_DIR="/data"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:gorelay]
command=gorelay
environment=PORT="8000",PYTHON_PORT="8001",DATA_DIR="/data"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
